import { Header, Sidebar } from '@/components'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex bg-white min-h-screen">
        <Sidebar />
        <div className="flex-grow text-gray-800">
          <Header />
          {children}
        </div>

      </body>
    </html>
  )
}
